#  - platform: coolix           # Compatible with Electra AC - Remore RC08C 
#  - platform: fujitsu_general  # Compatible with Fujitsu AC - Remote AR-RAH2E
#  - platform: zhlt01           # Compatible with Tornado AC - Remore ZH/EZ-01 
substitutions:
  device_name: "living-room-ac-remote"
  friendly_name: "Living-room-ac-remote"
  device_description: "Living room Fujitsu AC"
  room_name: Living
  climate_platform: fujitsu_general

esphome:
  name: ${device_name}
  comment: ${device_description}  
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging with verbose IR debugging
logger:
  level: VERY_VERBOSE
  logs:
    remote_receiver: VERBOSE
    remote_transmitter: VERBOSE
    remote.fujitsu_general: VERBOSE
    climate: VERY_VERBOSE

  
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

captive_portal:

# AHT10 uses I2C commonication on ESP32-C3 Supermini SCL (GPIO9) and SDA (GPIO10)
i2c:
  sda: GPIO21
  scl: GPIO22
    
sensor:
  - platform: aht10
    variant: AHT10
    temperature:
      name: "${room_name} room Temperature"
      id: ${room_name}_temperature
      accuracy_decimals: 1
    humidity:
      name: "${room_name} room  Humidity"
      id: ${room_name}_humidity
      accuracy_decimals: 1
    update_interval: 60s

# Simple Reciver KY022 connected to GPIO14 (D5) or GPIO GPIO4 (D2)
# The parameters are adjusted for AR-RAH2E it is 98% working 
remote_receiver:
  id: ac_ir_reciver
  pin:
    number: GPIO14
    inverted: true
  tolerance: 60%  
  filter: 125us    
  idle: 30ms      
  buffer_size: 4096
#  dump: all



# Simple Transmiter connected to DPIO13 (D7) or GPIO5 (D1)
# 2nd option instead of using a resistor, transistor, and IR LED, you can use PCB0100 
remote_transmitter:
  id: ac_ir_transmit
  pin: 
    number: GPIO13
#    number: GPIO5
    inverted: false
  carrier_duty_percent: 50%

# See https://esphome.io/components/climate/climate_ir.html for supported units
climate:
  - platform: fujitsu_general
    sensor: ${room_name}_temperature
    name: "${room_name} AC Climate Control"
    supports_heat: true    
    supports_cool: true  
    receiver_id: ac_ir_reciver
    transmitter_id: ac_ir_transmit
    visual:
      max_temperature: 30
      min_temperature: 16