esphome:
  name: "office ac remote"
  friendly_name: esp8266-test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+Dv9b6ovw8/uPLD2MEnpJGE5WptrF50aYlO9lCBufTw="

ota:
  - platform: esphome
    password: "3aa80c96fa2cd7e90b3524677be92a63"
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Test Fallback Hotspot"
    password: "l8FKr6x4bepa"

captive_portal:

# Temprature and humidity sensor ATH10 useing I2C peotocol 
i2c:

# On the ESP8266 D1 mini the I2C uses GPIO5 (D1) as SCL and GPIO4 (D2) as SDL
sensor:
  - platform: aht10
    variant: AHT10
    temperature:
      name: "Office Temperature"
      id: office_temperature
    humidity:
      name: "Office Humidity"
      id: office_humidity
    update_interval: 60s

# Simple Reciver
remote_receiver:
  id: ac_ir_reciver
  tolerance: 25%
  pin:
    inverted: true
    number: GPIO14 #D5
  dump: all

# Simple Transmiter
remote_transmitter:
  id: ac_ir_transmit
  pin: 
    number: GPIO13
    inverted: False
  carrier_duty_percent: 50%

climate:
  - platform: coolix
    sensor: office_temperature
    name: "My_office AC"
    supports_heat: True
    supports_cool: True
    receiver_id: ac_ir_reciver  
    transmitter_id: ac_ir_transmit    
    visual: 
      max_temperature: 30
      min_temperature: 17  